### ISSUE TITLE
 java.io.IOException

### ISSUE THREAD

**Issue by hujian1031** [GeekyAnts/flutter-bluetooth-adapter#5]
W/System.err( 5433): java.io.IOException: bt socket closed, read return: -1
W/System.err( 5433): 	at android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:434)
W/System.err( 5433): 	at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)
W/System.err( 5433): 	at java.io.InputStream.read(InputStream.java:162)
W/System.err( 5433): 	at com.aditya.bluetoothadapter.BluetoothadapterPlugin$SendRecieve.run(BluetoothadapterPlugin.java:377)

**Comment by viral-sangani** [comment]
Hi @hujian1031, we are unable to replicate this issue. Can you please provide steps to replicate this and provide more information about it?

**Comment by LimWC** [comment]
When the app is running in client mode, and another device running in server mode. The above output is shown when the app is disconnected by the device running in server mode.

**Comment by LimWC** [comment]
Is there any way to disconnect a device by using bluetoothadapater flutter library?

**Comment by vaibhiarora03** [comment]
hi @hujian1031 . did you find any solution for this issue?
